# Generated by Django 5.0.4 on 2024-04-11 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'наименование меню', 'verbose_name_plural': 'Наименования меню'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'наименование товара', 'verbose_name_plural': 'Наименования товарво'},
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.menu', verbose_name='Наименование меню'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
    ]
